POST https://tut-playerstate--h37f9gj.redpebble-0d6090f5.westeurope.azurecontainerapps.io/api/PlayerState
Content-Type: application/json

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "bars": [
    {
      "id": "6a291908-3186-4212-be55-82710d1dd772",
      "name": "string",
      "value": 0,
      "employees": [
        "33e093da-45fb-48c3-9f0d-ab125a708235"
      ],
      "ledger": [
        {
          "inventoryItemId": "b2af31fa-38ae-4ee0-9d2e-b542ceda5fa6",
          "count": 2
        }
      ],
      "popularity": 0,
      "district": {
        "id": "6f159dd5-1407-4603-991f-25e95332d284",
        "name": "string",
        "population": 0,
        "ecomonicRating": 0
      }
    }
  ],
  "funds": 0,
  "employees": [
    {
      "id": "33e093da-45fb-48c3-9f0d-ab125a708235",
      "name": "string",
      "species": {
        "id": "1ad434a6-f307-498c-9cad-5aca6dd30e7a",
        "name": "string"
      },
      "salary": 0,
      "age": 0
    }
  ]
}

###

GET https://tut-playerstate--h37f9gj.redpebble-0d6090f5.westeurope.azurecontainerapps.io/api/PlayerState?id=3fa85f64-5717-4562-b3fc-2c963f66afa6
Accept: application/json

###

POST https://tut-playerstate.thankfulpond-fb1cbc0f.northeurope.azurecontainerapps.io/api/PlayerCreation?firstBarName=Mos%20Eisley
Content-Type: application/json

{
  "firstBarName": "Mos Eisley"
}

###

PUT https://tut-playerstate.thankfulpond-fb1cbc0f.northeurope.azurecontainerapps.io/api/BarManagement/82ff4899-fcc3-4a65-8b4d-3fe0534e9137/c8c27432-35ca-4f85-af27-7d27cf4b410a?newBarType=Cantina
Content-Type: application/json

{}

###

GET https://tut-playerstate.thankfulpond-fb1cbc0f.northeurope.azurecontainerapps.io/api/PlayerState?id=82ff4899-fcc3-4a65-8b4d-3fe0534e9137
Accept: application/json

