name: 'Deploy Base Infrastructure'

on:
  push:
    branches:
      - main
    paths:
      - 'src/iac/**'
      - '.github/workflows/deploy_base_infrastructure.yaml'
  workflow_dispatch:

env:
  RESOURCE_GROUP: toolup-tuesday
  RESOURCE_GROUP_LOCATION: northeurope
    
jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    environment: production.azure
    permissions:
      id-token: write
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3.1.0
      - uses: 'azure/login@v1'
        name: 'Login to Azure'
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: 'azure/CLI@v1'
        with:
          azcliversion: 2.38.0
          inlineScript: |
            az group create -n ${{env.RESOURCE_GROUP}} --location ${{env.RESOURCE_GROUP_LOCATION}}
            az deployment group create --template-file './src/iac/core.bicep' -g ${{env.RESOURCE_GROUP}}



