name: Go Dependency Submission
on:
  push:
    branches:
      - main
    paths:
      - src/SpaceBar.PlayerDecisions/**
  workflow_dispatch:

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write

jobs:
  go-action-detection:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3.1.0

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"

      - name: Run snapshot action
        uses: actions/go-dependency-submission@v1
        with:
            # Required: Define the repo path to the go.mod file used by the
            # build target
            go-mod-path: src/SpaceBar.PlayerDecisions/go.mod
            #
            # Optional: Define the path of a build target (a file with a
            # `main()` function) If not defined, this Action will collect all
            # dependencies used by all build targets for the module, which may
            # include Go dependencies used by tests and tooling.
            go-build-target: src/SpaceBar.PlayerDecisions/main.go