on:
  push: 
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_player_state_api:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Build dotnet"
        run: dotnet build
        working-directory: src/SpaceBar.PlayerState/