name: 'Player Decision API'

on:
  push:
    branches:
      - main
    paths:
      - 'src/SpaceBar.PlayerDecisions/**'
      - '.github/workflows/player_decisions_api.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/SpaceBar.PlayerDecisions/**'  
      - '.github/workflows/player_decisions_api.yaml'  

env:
  IMAGE_NAME: spacebar/player-decisions
  MICROSERVICE_LOCATION: src/SpaceBar.PlayerDecisions/
  REGISTRY: ghrc.io

jobs:

  build_image:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
        
      - name: 'Build and Push Redirect Container Image'
        working-directory: ${{ env.MICROSERVICE_LOCATION }}
        run: |
          docker build . -t ${{ env.IMAGE_NAME }}:${{ github.sha }}
  deploy_image:
      if: github.event_name  == 'push' && github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3
        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: 'Build and Push Redirect Container Image'
          working-directory: ${{ env.MICROSERVICE_LOCATION }}
          run: |
            docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
