name: 'World Events Engine'
on:
  push: 
    branches:
      - main
    paths:
      - src/SpaceBar.WorldEventsEngine/**
      - .github/workflows/world_events_engine.yaml
        
  workflow_dispatch:

env:
  IMAGE_NAME: cloudwithchris/toolup-tuesday/spacebar/world-events-engine
  MICROSERVICE_LOCATION: src/SpaceBar.WorldEventsEngine/
  REGISTRY: ghcr.io
  RESOURCE_GROUP: toolup-tuesday

jobs:
  build_world_events_engine:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.1.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: "Build dotnet"
        run: dotnet build
        working-directory: ${{env.MICROSERVICE_LOCATION}}
  deploy_image:
    if: github.event_name  == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build_world_events_engine
    permissions:
      packages: write
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3.1.0
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: ${{ env.MICROSERVICE_LOCATION }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
  deploy_container_app:
      runs-on: ubuntu-latest
      needs: deploy_image
      environment: production.azure
      permissions:
        id-token: write
      steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3.1.0
        - uses: 'azure/login@v1'
          name: 'Login to Azure'
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        - uses: 'azure/CLI@v1'
          with:
            azcliversion: 2.38.0
            inlineScript: |
              az deployment group create --name 'world-events-engine-${{github.sha}}' --template-file './src/SpaceBar.WorldEventsEngine/iac/template.bicep' --parameters containerAppImage=${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{ github.sha }} containerRegistryPassword=${{ secrets.GITHUB_TOKEN }} -g ${{env.RESOURCE_GROUP}}